meta_product_name: "Star Wars App"
meta_title: "Star Wars App made with SWAPI - Star Wars API"
meta_description: "Find informations about characters, planets, species and starships"
meta_image: "star-wars.png"
